language: ruby

rvm: 2.2.4

addons:
  postgresql: "9.2"

services: postgresql

before_script:
  - psql -c 'create database classifurlr_test;' -U postgres
  - cp config/database.yml.example config/database.yml
  - mkdir -p tmp/cache

script: bundle exec rspec spec
